INSERT INTO prompt_templates (
    id,
    name,
    slug,
    category,
    description,
    notes,
    template_body,
    system_prompt,
    user_prompt_template,
    input_mode,
    provider,
    default_model,
    output_mode,
    schema_key,
    settings_json,
    input_contract_json,
    metadata_json,
    is_active,
    is_default,
    sort_order,
    version,
    created_at_utc,
    updated_at_utc
)
SELECT
    '7eb964ee-dab2-4c56-b6f8-4f3001c5c101'::uuid,
    'Kie Gemini 3 Pro Test',
    'kie-gemini-3-pro-test',
    'reasoning_test',
    'Smoke-test prompt template for Kie AI Gemini 3 Pro.',
    'Use this template to verify Kie AI provider wiring and prompt execution.',
    'You are a precise test assistant. Follow the user request exactly.',
    'You are a precise test assistant. Follow the user request exactly.',
    E'{{input_json}}',
    'json_manual',
    'kie_ai',
    'gemini-3-pro',
    'text',
    NULL,
    '{"temperature":0.2}'::jsonb,
    '{"required":["query"]}'::jsonb,
    '{"provider":"kie_ai","family":"gemini","purpose":"reasoning_test"}'::jsonb,
    true,
    false,
    210,
    1,
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM prompt_templates WHERE slug = 'kie-gemini-3-pro-test'
);

INSERT INTO prompt_templates (
    id,
    name,
    slug,
    category,
    description,
    notes,
    template_body,
    system_prompt,
    user_prompt_template,
    input_mode,
    provider,
    default_model,
    output_mode,
    schema_key,
    settings_json,
    input_contract_json,
    metadata_json,
    is_active,
    is_default,
    sort_order,
    version,
    created_at_utc,
    updated_at_utc
)
SELECT
    '0fd81c86-4670-4dbe-bb96-2e2eb9ce4b2b'::uuid,
    'Kie Gemini 2.5 Flash Test',
    'kie-gemini-2-5-flash-test',
    'reasoning_test',
    'Smoke-test prompt template for Kie AI Gemini 2.5 Flash.',
    'Use this template to verify the faster Kie AI Gemini 2.5 Flash path.',
    'You are a precise test assistant. Follow the user request exactly.',
    'You are a precise test assistant. Follow the user request exactly.',
    E'{{input_json}}',
    'json_manual',
    'kie_ai',
    'gemini-2.5-flash',
    'text',
    NULL,
    '{"temperature":0.2}'::jsonb,
    '{"required":["query"]}'::jsonb,
    '{"provider":"kie_ai","family":"gemini","purpose":"reasoning_test"}'::jsonb,
    true,
    false,
    220,
    1,
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM prompt_templates WHERE slug = 'kie-gemini-2-5-flash-test'
);

INSERT INTO prompt_templates (
    id,
    name,
    slug,
    category,
    description,
    notes,
    template_body,
    system_prompt,
    user_prompt_template,
    input_mode,
    provider,
    default_model,
    output_mode,
    schema_key,
    settings_json,
    input_contract_json,
    metadata_json,
    is_active,
    is_default,
    sort_order,
    version,
    created_at_utc,
    updated_at_utc
)
SELECT
    '69075d2f-e75d-4ccb-bfac-f55a9ef14d69'::uuid,
    'Kie Gemini 2.5 Pro Test',
    'kie-gemini-2-5-pro-test',
    'reasoning_test',
    'Smoke-test prompt template for Kie AI Gemini 2.5 Pro.',
    'Use this template to verify the Kie AI Gemini 2.5 Pro reasoning path.',
    'You are a precise test assistant. Follow the user request exactly.',
    'You are a precise test assistant. Follow the user request exactly.',
    E'{{input_json}}',
    'json_manual',
    'kie_ai',
    'gemini-2.5-pro',
    'text',
    NULL,
    '{"temperature":0.2}'::jsonb,
    '{"required":["query"]}'::jsonb,
    '{"provider":"kie_ai","family":"gemini","purpose":"reasoning_test"}'::jsonb,
    true,
    false,
    230,
    1,
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM prompt_templates WHERE slug = 'kie-gemini-2-5-pro-test'
);
